version: '2'

services:

  resizer:
    build: .
    depends_on:
      - mysql
    env_file: secret.env
    volumes:
      - .:/go/src/github.com/syoya/resizer
    ports:
      - 80:80

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'resizer'
